# Created using wingetcreate

PackageIdentifier: Any.do.Any.do
PackageVersion: 4.2.155.9593
PackageLocale: en-US
Publisher: Any.do
PackageName: Any.do
License: Copyright (c) Any.do 2021
ShortDescription: Any.do Desktop
ManifestType: defaultLocale
ManifestVersion: 1.0.0
